apiVersion: v1
kind: Secret
metadata:
  name: birthday-app-secret
type: Opaque
data:
  DB_USER: {{ .Values.db.postgresqlUsername | b64enc }}
  DB_PASSWORD: {{ .Values.db.postgresqlPassword | b64enc }}
