replicaCount: 2

image:
  repository: birthday-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

db:
  postgresqlUsername: postgres
  postgresqlPassword: strongpassword
  postgresqlDatabase: mydb
  persistence:
    size: 1Gi
